@startuml генерация тестов

!pragma useVerticalIf on

start
:Проверка корректности эталонного решения;

if () then (Нет ошибок)
    group Генерация тестов
        repeat
            if () then (Количество ошибок больше 4)
                #pink :Завершение генерации из-за большого количества ошибок;
                break;
            endif
            :Запустить генератор;
            :Запустить эталонное решение на сгенерированных данных;
            if () then (Произошла ошибка компиляции)
                #pink :Добавить запись об ошибке компиляции;
                break;
            elseif () then (Произошла ошибка выполнения программы)
                :Добавить запись об ошибке выполнения;
                :Инкрементировать счётчик ошибок;
            else (Генерация прошла успешно)
                :Добавить новый тестовый пример;
            endif
        repeat while () is (Нужно сгенерировать ещё тест)
    end group
endif

stop

@enduml