@startuml

left to right direction

actor Пользователь as u

u --> (Импорт yaml файлов)
u --> (Импорт MoodleXml файлов)
u --> (Редактирование текста файлов)
u --> (Экспорт файлов)
u --> (Создание и редактирование задачи)
u --> (Отображение ошибок)

@enduml