@startuml

left to right direction

actor Пользователь as u

u --> (Импортировать yaml файлы)
u --> (Импортировать MoodleXml файлы)
u --> (Редактировать текст файлов)
u --> (Экспортировать файлы)
u --> (Создавать и редактировать задачи)

@enduml