@startuml проверка коррктности эталонного решения

!pragma useVerticalIf on

start
group Проверка корректности эталонного решения
repeat
    :Запустить решение на тестовом примере;
    if () then (Произошла ошибка компиляции)
        #pink :Добавить запись об ошибке компиляции;
        break;
    elseif () then (Произошла ошибка выполнения программы)
        :Добавить запись об ошибке выполнения;
    elseif () then (Вывод решения не совпадает с ожидаемым)
        :Добавить запись о неожиданном ответе;
    endif
repeat while () is (Ещё есть тестовые примеры) not (Тестовые примеры закончились)
end group
if () then (Нет ошибок)
    :Генерация тестов;
endif

@enduml