openapi: 3.0.3
info:
  title: SimpleCode
  description: SimpleCode это веб-приложение для создания задач по программированию с возможностью экспорта в формате MoodlXML
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /promptToSandbox:
    post:
      summary: Сгенерировать файл-представление для написанной задачи
      operationId: generate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptToSandbox'
        required: true
      responses:
        '201':
          description: Эталонное решение прошло все тесты и из песочницы вернулись сгенерированные тесты
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Эталонное решение либо не прошло все тесты, либо при выполнении в песочнице возникла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobeCode:
                    type: integer
                    description: |
                      Код ответа из песочницы JobeInABox:
                      
                      11 - Compilation error. The cmpinfo field should offer further explanation
                      
                      12 - Runtime error. The job compiled but threw an exception at run time that isn't covered by any of the more-specific errors below.
                      
                      13 - Time limit exceeded. The job was killed before it ran to completion as a result of the server-specified time limit (or a possible time limit specified via the parameters field of the job request) being reached.
                      
                      15 - OK. The run ran to completion without any exceptions.
                      
                      17 - Memory limit exceeded. The job was killed before it ran to completion as a result of the server-specified maximum memory limit (or a possible memory limit specified via the parameters field of the job request) being reached.
                      
                      19 - Illegal system call. The task attempted a system call not allowed by this particular server.
                      
                      20 - Internal error. Something went wrong in the server. Please report this to an administrator.
                      
                      21 - Server overload. No free Jobe user accounts. Probably something has gone wrong.
                  cmpInfo:
                    type: string
                    description: any output generated by the compiler (if there is one) at compile time.

components:
  schemas:
    PromptToSandbox:
      type: object
      required:
        - answerProgram
        - testCases
        - testGeneratorProgram
      properties:
        answerProgram:
          type: string
        testCases:
          type: array
          maxItems: 100
          items:
            type: string
        testGeneratorProgram:
          type: string
