spring:
  application:
    name: SimpleCode
  docker:
    compose:
      file: jobe-compose.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  tomcat:
    max-http-form-post-size: 20MB

application:
  polygon:
    problem:
      name:
        xpath: /problem/names/name
        attribute: value
        default-value: Unknown
      time-limit-millis:
        xpath: /problem/judging/testset/time-limit
        default-value: 1000
      memory-limit:
        xpath: /problem/judging/testset/memory-limit
        default-value: 5MB
      statement:
        xpath: /problem/statements/statement[@type='application/x-tex'][@language='russian']
        attribute: path
      executables:
        main-solution:
          xpath: /problem/assets/solutions/solution[@tag='main']/source
        other:
          xpath: /problem/files/executables/executable/source
        path-attribute: path
        language-attribute: type
      test-sets:
        xpath: /problem/judging/testset
        name:
          attribute: name
        stdin-path-pattern:
          xpath: input-path-pattern
        expected-path-pattern:
          xpath: answer-path-pattern
        tests:
          xpath: tests/test
          sample:
            attribute: sample
          method:
            attribute: method
          cmd:
            attribute: cmd

jobe:
  client:
    timeout: 20s
#    base-url: http://localhost:8081/jobe/index.php/restapi
    base-url: http://jobe/jobe/index.php/restapi
    max-errors-in-row: 5