spring:
  application:
    name: SimpleCode
  docker:
    compose:
      file: jobe-compose.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

application:
  polygon:
    problem:
      name:
        xpath: /problem/names/name
        attribute: value
        default: Unknown
      time-limit-millis:
        xpath: /problem/judging/testset/time-limit
        default: 1000
      memory-limit:
        xpath: /problem/judging/testset/memory-limit
        default: 5MB
      executables:
        main-solution:
          xpath: /problem/assets/solutions/solution[@tag='main']/source
        other:
          xpath: /problem/files/executables/executable/source
        path-attribute: path
        language-attribute: type
      test-sets:
        xpath: /problem/judging/testset
        name:
          attribute: name
        input-path-pattern:
          xpath: input-path-pattern
        tests:
          xpath: tests/test
          sample:
            attribute: sample
          method:
            attribute: method
          cmd:
            attribute: cmd

jobe:
  client:
    timeout: 10s
    base-url: http://localhost:8081/jobe/index.php/restapi/runs
    max-errors-in-row: 5
  responses:
    compilation-error: 11
    runtime-error: 12
    time-limit-exceeded: 13
    ok: 15
    memory-limit-exceeded: 17
    illegal-system-call: 19
    internal-error: 20
    server-overload: 21