services:
  server:
    build:
      context: .
    container_name: server
    depends_on:
      - jobe
    networks:
      - course-work
    ports:
      - 8080:8080

  jobe:
    image: trampgeek/jobeinabox:latest
    container_name: jobe
    networks:
      - course-work

networks:
  course-work:
