services:
  server:
    build: .
    container_name: server
    depends_on:
      - jobe
    networks:
      - course-work
    ports:
      - 8080:8080
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  jobe:
    image: trampgeek/jobeinabox:latest
    container_name: jobe
    networks:
      - course-work

networks:
  course-work:
